import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers'
import Header from '@/components/header'

const soraSans = Sora({
  variable: '--font-sora-sans',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${soraSans.variable} antialiased`}>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
